### ISSUE TITLE
Improve client credentials entropy

### ISSUE THREAD

**Issue by msokolovski** [apifest/apifest-oauth20#83]
Currently the code for generation of client id and client secret ([RandomGenerator#96](https://github.com/apifest/apifest-oauth20/blob/master/apifest-oauth20/src/main/java/com/apifest/oauth20/RandomGenerator.java#L96)) has a weak entropy, which leaves gap for collisions and authentication errors.

The entropy can be improved with the following changes:
- switch all input generation components (random, time, thread ID) to Strings, in order to avoid numeric addition and produce more distinctive input string
- switch time component from milliseconds to nanoseconds, in order to achieve more frequent changes of the specific input
- add free memory as component for input generation

**Comment by rossitsaborissova** [comment]
Thanks for  that improvement!
